-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.usuarios
(
    id serial,
    nombre character varying(15)[] NOT NULL,
    passwd character varying(20)[] NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.comentarios
(
    id serial,
    id_usuario integer NOT NULL,
    texto character varying(20)[] NOT NULL,
    id_post integer
);

CREATE TABLE IF NOT EXISTS public.post
(
    id serial,
    user_id integer NOT NULL,
    titulo_post character varying(25)[] NOT NULL,
    contenido_post character varying(40)[] NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.comentarios
    ADD FOREIGN KEY (id_post)
    REFERENCES public.post (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.comentarios
    ADD FOREIGN KEY (id_usuario)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.post
    ADD FOREIGN KEY (user_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;